### ISSUE TITLE
Rebasing bug

### ISSUE THREAD

**Issue by s3rius** [s3rius/pre_commit_hooks#5]
If you performing rebase, pre-commit fails to pass because of this error:

```
Traceback (most recent call last):
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/bin/commit_msg_prefix", line 8, in <module>
    sys.exit(main())
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/commit_msg_prefix/entry.py", line 68, in main
    ticket = get_current_ticket()
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/utils/git.py", line 44, in get_current_ticket
    branch_name = get_active_branch_name()
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/utils/git.py", line 33, in get_active_branch_name
    return str(git.Repo(".").active_branch.name)
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/lib/python3.8/site-packages/git/repo/base.py", line 758, in active_branch
    return self.head.reference
  File "/home/s3rius/.cache/pre-commit/repod72pqwc8/py_env-python3.8/lib/python3.8/site-packages/git/refs/symbolic.py", line 272, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'd62f972ecf334c752f30ef14e906dfa81d2484db'
```

**Comment by s3rius** [comment]
Problem solved.
